### ISSUE TITLE
Pretvorba html - program za uvoz

### ISSUE THREAD

**Issue by darjapet** [darjapet/APPR-2017#1]
Pri pisanju programa za uvoz in pretvorbi števil zaznanih kot character, mi Rstudio napiše napako, da funkcija locale ne obstaja. V čem je napaka?

**Comment by jaanos** [comment]
Funkcija `locale` je del knjižnice `readr`, tako da bo treba najprej to uvoziti - lahko kar poženeš `lib/libraries.r`, da naložiš vse potrebne knjižnice (po potrebi lahko tja dodaš še druge knjižnice, ki jih boš potrebovala). Potem bodo na voljo tudi funkcije `read_csv(2)` za branje iz CSV. V R so sicer že na voljo funkcije `read.csv(2)` (s piko namesto podčrtaja), a so funkcije iz knjižnice `readr` nekoliko bolj fleksibilne.

Mimogrede, uvoz kar vključi v poročilo (namesto `uvoz/uvoz.r` vključi svoj program) - potem lahko morda prikažeš še kako tabelo. Preostanek poročila, ki se nanaša na vzorec, za zdaj kar pobriši (boš sproti dodajala svojo vsebino).

**Comment by darjapet** [comment]
Pri uvozu imam problem, saj so podatki napisani kot 40.6 million. Kako spremenim, da odstrani besedo million in zamenja z dejansko številko?

**Comment by jaanos** [comment]
Lahko si pomagaš s funkcijo `parse_number` iz knjižnice `readr`, ki pri pretvorbi v število ignorira vse po koncu števila, nato pa vse skupaj pomnožiš z `1000000`:
```R
tabela1$`mednarodni turisti 2015` <- (tabela1$`mednarodni turisti 2015` %>% parse_number()) * 1000000
```
Razpredelnico bo seveda potrebno še pretvoriti v obliko *tidy data*.

Mimogrede, svetujem, da se izogibaš presledkom (in šumnikom) v imenih stolpcev - tako stolpcev ne bo potrebno podajati znotraj \`\`. Tudi ukaza `View` ne vključuj v sam program - ko boš prevajala poročilo, ne boš želela, da ti vsakič odpre uvožene podatke.

**Comment by darjapet** [comment]
Pri spremembi uvoza sem zdaj napisala sledeči program in me zanima če je v redu:

tabela2 <- read.csv(file = "podatki/st_nocitev.csv", head = TRUE, sep=",")
tabela2$vrednost <- NULL
colnames(tabela2) <- c("leto", "drzava", "domacini/tujci", "vrednost", "vrsta nocitve", "stevilo gostov")
View(tabela2)
_________________________
A ne morem nažalost izvesti, saj mi napiše sledečo napako pri poskusu pusha:

To https://github.com/darjapet/APPR-2017.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/darjapet/APPR-2017.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by jaanos** [comment]
Uvoz je v grobem načeloma v redu - kot sem napisal, bo morda bolje, če uporabiš `read_csv` iz knjižnice `readr`, s katerim lahko nastaviš tudi znak za ločilo tisočic, poleg tega pa je potrebno nastaviti še znak za manjkajoče vrednosti:
```R
tabela2 <- read_csv(file = "podatki/st_nocitev.csv", locale = locale(grouping_mark = ","), na = ":")
```
Stolpca `vrednost` pred preimenovanjem nimaš, tako da ga ni potrebno brisati. Pri imenih stolpcev svetujem, da se izogibaš šumnikom, presledkom, in drugim posebnim znakom, kot npr. `/` (ali katerikoli operator v R-ju). Ukaza `View` ne vključuj v program, saj ne želiš, da bi se ti razpredelnica prikazala vsakič, ko prevedeš poročilo.

Napako pri pushu ti javi, ker imaš na GitHubu commit, ki ga pri sebi še nimaš. Če dobiš to napako, naredi pull - prišlo bo do združitve, morebiti bo potrebno še razrešiti kakšne konflikte. Ko te razrešiš (če je potrebno), naredi commit, potem boš pa lahko naredila push. V izogib takšnim situacijam je najbolje, če pred začetkom dela vedno narediš pull in tako k sebi pridobiš aktualno različico.

**Comment by darjapet** [comment]
Pri uvozu podatkov mi z zgornjo formulo še vedno javlja napako, ki je ne znam odstraniti:

> sl <- locale("sl", decimal_mark = ".", grouping_mark = ",")
> tabela2 <- read_csv(file = "podatki/st_nocitev.csv", locale = sl, na = ":") %>%
+ filter(GEO != "European Union (28 countries)") %>%
+ filter(NACE_R2 != "Total - all NACE activities")
Parsed with column specification:
cols(
  TIME = col_integer(),
  GEO = col_character(),
  INDIC_TO = col_character(),
  UNIT = col_character(),
  NACE_R2 = col_character(),
  Value = col_number()

**Comment by jaanos** [comment]
To ni napaka - je samo obvestilo, kako so bili uvoženi posamezni stolpci.

**Comment by darjapet** [comment]
Se mi zdi, da mi je sedaj uspelo opraviti celoten uvoz - je tabela 2 potem tako že v obliki tidy data?

**Comment by jaanos** [comment]
Ja `tabela2` je v obliki *tidy data*. Pri `tabela3` se uvoz sicer ustavi, saj spremenljivke `zaposljenost_v_turizmu` nimaš definirane.

V poročilu tudi pazi, da pravilno navajaš imena datotek - tvojemu programu je ime `uvoz1.R` (velika črka v končnici), tako da naj bo tako tudi, ko ga pokličeš, saj so nekateri sistemi na to občutljivi. Pazi še, kar sem zgoraj napisal glede `View` in preostanka poročila.

**Comment by darjapet** [comment]
View imam trenutno uključen, samo da sedaj vidim kako mi program pokaže podatke.
Ostalo sem popravila.
Hvala
