### ISSUE TITLE
Vizualizacija

### ISSUE THREAD

**Issue by darjapet** [darjapet/APPR-2017#2]
Pri uvozu zemljevida mi napiše naslednjo napako:
Error in eval(expr, envir, enclos) : 
  could not find function "uvozi.zemljevid"

Na faksu mi je normalno odprlo, na domačem računalniku pa očitno nimam nameščenega katerega paketa?

**Comment by darjapet** [comment]
Sem ugotovila, kje je bila napaka.

**Comment by jaanos** [comment]
Zadevo lahko potem zapreš - klikni na *Close issue* (oziroma *Close and comment*, če ob tem še kaj napišeš).
