### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by darjapet** [darjapet/APPR-2017#3]
V RStudiju lahko spremembe samo commitam, ne morem pa jih push-at na git - kako bi to lahko popravila?

**Comment by jaanos** [comment]
Ali lahko natančno opišeš, kaj se zgodi - kakšno napako javi? Pomagal bi tudi posnetek zaslona - sliko lahko enostavno potegneš v polje za odgovor.

**Comment by darjapet** [comment]
Lahko dodam komentarje, vendar ne morem shraniti na GIT.
![slika1](https://cloud.githubusercontent.com/assets/26812652/26564678/7743d6de-44e4-11e7-84d6-c4b2a3a8839e.jpg)
![slika2](https://cloud.githubusercontent.com/assets/26812652/26564677/773fd390-44e4-11e7-8483-23d22a0045e5.jpg)
![slika3](https://cloud.githubusercontent.com/assets/26812652/26564679/774435b6-44e4-11e7-8603-f2f75acc9c6a.jpg)

**Comment by jaanos** [comment]
Izgleda, kot da si iz GitHuba potegnila datoteko ZIP in nato v nastalem imeniku začela nov repozitorij. Če je tako, bi se morali po kliku na *History* (zadnja slika, levo zgoraj) pojaviti samo commiti, ki si jih nazadnje naredila pri sebi (torej brez tistih, ki so že na GitHubu).

V tem primeru bo najlažje, če enostavno iz RStudia še enkrat kloniraš stanje z GitHuba - desno zgoraj klikni na ime projekta, nato pa *New Project...* in *Version Control*, *Git*, potem pa vneseš HTTPS naslov tvojega repozitorija (natančnejša [navodila](https://ucilnica.fmf.uni-lj.si/mod/wiki/view.php?pageid=126) so na spletni učilnici). Ko boš imela pri sebi to kopijo, v Raziskovalcu odpri imenik, kjer si do sedaj delala (po prvi sliki sklepam, da je to `C:\Users\Darja\Desktop\APPR-2017-master`) in vse datoteke skopiraj v imenik z novo kopijo repozitorija (ne kopiraj celotnega imenika, saj vsebuje gitove skrite datoteke). Potem bi se morale spremembe pojaviti v RStudiu, kjer lahko narediš commit in nato push. Ko to uspe in so najnovejše spremembe na GitHubu, bo najbolje, da stari projekt (kjer push ne deluje) pobrišeš.

Če pa commite z GitHuba že imaš, bo potrebno samo nastaviti [oddaljeno točko](https://ucilnica.fmf.uni-lj.si/mod/wiki/view.php?pageid=126#toc-23) `origin` na HTTPS naslov tvojega repozitorija (če še ni) ter potem prvi push narediti s TortoiseGitom - potem bi moralo delovati tudi v RStudiu.

**Comment by darjapet** [comment]
Uspelo mi je popraviti. Lp
