### ISSUE TITLE
Zemljevid in predstavitev

### ISSUE THREAD

**Issue by jaanos** [darjapet/APPR-2017#4]
Da boš pripravljena na predstavitev naslednji teden, prosim dodaj v poročilo grafe in zemljevide, ki jih boš takrat prikazala. Teh ne izrisuj v `vizualizacija.r` (tam jih lahko pripraviš), pač pa vsakega izriši v bloku kode na želenem mestu v poročilu. S številom grafov in zemljevidov seveda ni potrebno pretiravati - za vsakega pa napiši, kaj prikazuje in kaj si se iz njega naučila. Iz poročila in `vizualizacija.r` tudi pobriši del, ki je ostal iz vzorca, da bo program tekel brez napak in se bo poročilo lahko prevedlo.

Pri zemljevidu poskrbi za ustrezne meje, prav tako se izogni eksponentni notaciji v legendi. Najbrž želiš prikazati podatke iz stolpca `noc` iz razpredelnice `nocitve`. Potem lahko zemljevid pripraviš npr. tako:
```R
z <- ggplot() + geom_polygon(data = left_join(evropa, nocitve, by = c("name_sort" = "drzava")),
                             aes(x = long, y = lat, group = group, fill = noc/1e6)) +
  coord_map(xlim = c(-25, 40), ylim = c(32, 72)) +
  guides(fill = guide_colorbar(title = "Nočitve (milijoni)"))
```

**Comment by darjapet** [comment]
Pri seštevanju imam problem, saj so nekatere vrednosti NA in ko sešteje mi napiše, da je vsota NA. Kako bi te vrednosti že pred seštevanjem izbrisala iz tabele?

**Comment by jaanos** [comment]
Če hočeš pri seštevanju ignorirati vrednosti `NA`, funkciji `sum` dodaj parameter `na.rm = TRUE`. Če bi pa želela pobrisati vrstice z vrednostmi `NA`, lahko uporabiš funkcijo `drop_na` iz knjižnice `tidyr`.

Mimogrede, pri grafu `g2` nadomesti `%>%` pred `aes` z vejico, da bo deloval. Kot sem že napisal v #1, ukaza `View` ne uporabljaj v programu (v `uvoz1.R` se pojavi na dveh mestih).

**Comment by darjapet** [comment]
Želim prikazati stolpični diargam, v katerem bodo na x osi panoge turizma, na y pa število zaposlenih v posamezni panogi. V sledeči kodi mi javlja napako a pri vsoti ne prepozna stevilo_zaposlenih:
`g4 = ggplot(tabela3 %>% 
              group_by(panoga_turizma, drzava) %>%
              summarise(zaposleni = sum(stevilo_zaposlenih, na.rm = TRUE))%>%
              group_by(panoga_turizma),
            aes(x = panoga_turizma, y = zaposleni, color = stevilo_zaposlenih)) + geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))`

**Comment by jaanos** [comment]
Ko narediš `group_by` in `summarise`, se ohranijo le tisti stolpci, ki jih navedeš v `group_by` in jih definiraš v `summarise`. Stolpca `stevilo_zaposlenih` v tako agregirani razpredelnici torej več nimaš.

Če prav razumem, želiš prikazati vsote podatkov za vsa leta, vse države, vse starosti in vse vrste zaposlitve (morda bi se bilo bolj smiselno omejiti na eno leto, da bodo same številke kaj povedale). To bi šlo nekako tako:
```R
g4 <- ggplot(tabela3 %>% group_by(panoga_turizma) %>%
               summarise(zaposleni = sum(stevilo_zaposlenih, na.rm = TRUE)),
             aes(x = panoga_turizma, y = zaposleni)) + geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
Kot, pod katerim se prikažejo oznake osi x, sem zmanjšal, da te vzamejo manj prostora. Seveda lahko prirediš tako, da bo v poročilu lepo izgledalo.

**Comment by darjapet** [comment]
Pri zadnji pa sem želela prikazati število turistov v različnih vrstah prenočišč glede na to ali so domačini ali tujci. Ali je možno da bi v stolpičnem diagramu prokazala dva stolpca - enega za tujce in enega za domačine? Sedaj imam narejena dva ločena grafa.

Sem omejila graf o zaposlitvi na leto 2015, kakor sem želela, a sem očitno prej pozabila zapisati v kodo.

**Comment by jaanos** [comment]
Lahko - pri `aes` podaj parameter `fill = domacini_tujci`, da ti bo ti kategoriji ločilo pri barvi (seveda uporabi razpredelnico brez te delitve), pri `geom_bar` pa dodaj še parameter `position = "dodge"`, da se stolpca prikažeta en zraven drugega (sicer bi bil en nad drugim). Namesto `geom_bar` lahko uporabiš tudi `geom_col` - gre za isto stvar, le da je parameter `stat = "identity"` impliciten in ga ni treba podajati.

**Comment by darjapet** [comment]
Hvala. Sedaj sem pripravila vse grafe, ki sem jih želela - jih je dovolj?

**Comment by jaanos** [comment]
Bo v redu - kot rečeno, bolj kot na samo količino grafov pazi na to, da bodo grafi zanimivi in da lahko o njih kaj poveš, se iz njih kaj naučiš. Sedaj poskrbi še za poročilo.

**Comment by darjapet** [comment]
Sem uredila tudi poročilo, edino ko ga poženem mi dopisuje nasljednja opozorila - je to vseeno ali bi se kako dalo popraviti?
![brez naslova](https://user-images.githubusercontent.com/26812652/26854096-f68e8ac0-4b14-11e7-9181-1555e5a97e85.jpg)

**Comment by jaanos** [comment]
V glave blokov kode, kjer se ti pojavljajo ta opozorila, dodaj parameter `warning = FALSE`, pa se opozorila ne bodo izpisovala v poročilo.

Drugega opozorila se lahko sicer znebiš tudi tako, da pred združevanjem z zemljevidom stolpec `drzava` v razpredelnici `nocitve` pretvoriš v faktor z istimi vrednostmi kot stolpec `name_sort` v zemljevidu. Tako lahko zemljevid narediš tako:
```R
zemljevid <- ggplot() +
  geom_polygon(data = evropa %>%
                 left_join(nocitve %>%
                             mutate(drzava = parse_factor(drzava, levels(evropa$name_sort))),
                           by = c("name_sort" = "drzava")),
               aes(x = long, y = lat, group = group, fill = noc/1e6)) +
  coord_map(xlim = c(-25, 40), ylim = c(32, 72)) +
  guides(fill = guide_colorbar(title = "Nočitve (milijoni)"))
```
Trenutno dobiš sicer še opozorilo, ker se imeni za Makedonijo ne ujemata - lahko ga popraviš v zemljevidu na isti način, kot si za Slovaško.

**Comment by jaanos** [comment]
Bom kar dodal povezavo do trenutnega commita dodal na [repozitorij za zagovore](https://github.com/jaanos/APPR-2017-zagovori). Če boš do predstavitve še kaj spreminjala, odpri issue na repozitoriju za zagovore, da posodobim povezavo - tam si preberi natančnejša navodila.
