### ISSUE TITLE
Preimenovanje podatkov

### ISSUE THREAD

**Issue by darjapet** [darjapet/APPR-2017#5]
Pri prikazanih tabelah imam podatke na x osi napisane v angleščini in prav tako podatke v legendi. Zanima me, kje bi lahko to popravila ter nastavila nova imena za vrednosti?

**Comment by jaanos** [comment]
Morda bo najlažje, če si pripraviš nekakšen slovar, kjer zbiraš prevode, npr.
```R
slovar <- c(
  "Camping grounds, recreational vehicle parks and trailer parks" = "Kampiranje",
  "Holiday and other short-stay accommodation" = "Počitnice",
  "Hotels and similar accommodation" = "Hoteli",
  "Total nights spent by non-residents" = "Tujci",
  "Total nights spent by residents" = "Domačini"
)
```
Ker so angleški nizi imena vnosov vektorja `slovar`, ga lahko indeksiraš s tvojimi podatki, npr.
```R
g5 <- ggplot(domacini_tujci,
             aes(x = slovar[vrsta_nocitve], y = gosti / 1e9,
                 fill = slovar[domacini_tujci])) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x="vrsta nočitve", y="število gostov") +
  guides(fill = guide_legend(title = "Vrsta nočitev"))
```
Dodal sem še naslov legende.

**Comment by darjapet** [comment]
Pri G2 in G3 imam problem, saj je črtni graf in mi podana formula ne sprmeni naslova v legendi.

Pri zemljevidu sem želela odstraniti long in lat, vendar mi zapis, ki sem ga našla ne spremeni nič - kako bi to lahko spremenila?

**Comment by jaanos** [comment]
Parameter pri `guides` naj bo tak, kot pri prikazenem podatku v `aes`. Njegova vrednost je odvisna od tipa legende - pri `g2` imaš torej lahko `guides(color = guide_legend(title = "Država"))` (in podobno pri `g3`).

Če hočeš odstraniti oznake osi, zemljevidu prišteješ `xlab("") + ylab("")`.

**Comment by darjapet** [comment]
Dodala sem že sa spremembo osi, vedar mi ni registriralo in je pustilo long in lab - ne vem kje je napaka.

**Comment by jaanos** [comment]
Spremembo oznak osi si naredila na praznem zemljevidu, ki se v poročilu ne prikaže in ga lahko odstraniš. Da ti bo odstranilo oznake osi v poročilu, jih spremeni tam, kjer definiraš spremenljivko `zemeljvid` (podaj kar prazna niza, brez pike).
