### ISSUE TITLE
Zgovor projekta

### ISSUE THREAD

**Issue by darjapet** [darjapet/APPR-2017#6]
Je možno da bi imela projekta zagovor v torek?

**Comment by jaanos** [comment]
Poročilo ti trenutno prevede, tako da bom dodal povezavo na repozitorije za zagovore. Ko urediš še #5 in #7, mi javi, da posodobim povezavo.

Glede termina zagovora se domeni s profesorjem.

**Comment by darjapet** [comment]
Pri zagonu same aplikacije mi ne požene, vendar mi prevede v poročilo in lahko uporabljam tam. To je moje končno poročilo in bi ga rada dodala med repozitorije za zagovore.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo. Če boš še kaj spreminjala, mi javi, da ponovno posodobim.

Še nekaj pripomb:
* Kot sem že napisal v #7, poskrbi, da ti v Shiny aplikaciji prikaže število zaposlenih za Nemčijo.
* Tudi v Shiny aplikaciji se izogibaj temu, da bi na osi grafa številke bile v eksponentni notaciji. Pri prikazu podatkov za število gostov torej podatke deli npr. z 100000 (to lahko narediš kar v `summarise`) ter si pripravi ustrezno spremenljivko za oznako osi x.
* Besedilo `tukaj bodo podatki` nad grafom odstrani.

**Comment by darjapet** [comment]
Sem dodala še nekaj zadnjih popravkov in bi prosila, če posodobite povezavo.

Hvala za vso pomoč pri izdelavi projekta.
LP

**Comment by jaanos** [comment]
Sem posodobil povezavo. Naj opozorim, da ti sedaj ne prikazuje števila gostov za Nemčijo.
