### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by darjapet** [darjapet/APPR-2017#7]
V shinyju bi si želela narediti, da uporabnik izbere leto ter državo, potem pa se izriše stolpični diagram, ki prikazuje v enem stolpcu število zaposlenih in v drugem število gosstov.

1. v ui.R imam problem pri selectInput, kjer sem za države naredila slovar, tko da bodo v slovenščini - imam le problem, da ne vem kam besedo slovar umestiti, da mi bo prevedlo.

2. pri server.R ne vem kako pridobiti željene podatke - za število turistov bi rabila sešteti po vseh panogah v eni tabeli in za število zaposlenih po vseh panogah v drugi tabeli ter potem skupaj dati v željen graf.

**Comment by jaanos** [comment]
V `ui.R` lahko izbirnik narediš tako:
```R
                 selectInput("drzava", "Država:", choices = c("Belgija" = "Belgium",
                                                              "Bolgarija" = "Bulgaria",
                                                              ...),
                             multiple = FALSE)
```
Tukaj so torej imena vektorja prikazana imena, vrednosti pa so tiste, po katerih bo potekalo filtriranje.

Kolikor vidim, bi lahko podatke iz obeh tabela združila tako:
```R
  output$graf <- renderPlot({
    data <- rbind(tabela2 %>% filter(drzava == input$drzava, leto == input$leto) %>%
                    summarise(stevilo = sum(stevilo_gostov, na.rm = TRUE)) %>%
                    mutate(tip = "gostje"),
                  tabela3 %>% filter(drzava == input$drzava, leto == input$leto) %>%
                    summarise(stevilo = sum(stevilo_zaposlenih, na.rm = TRUE)) %>%
                    mutate(tip = "zaposleni"))
    ggplot(data, aes(x = tip, y = stevilo)) + geom_col() + ylab("Število oseb")
  })
```
Potem v `ui.R` graf prikažeš s `plotOutput("graf")` na želenem mestu. Sicer pa tak pristop odsvetujem, saj so številke neprimerljive in število zaposlenih ne bo vidno. Svetujem, da raje podatke prikažeš na dveh grafih, z leti na osi x.

**Comment by darjapet** [comment]
Sem spremenila koncept, tako da izbereš državo in potem ali zaposleni ali gostje in da izriše graf. Tako sem naredila data1 in data2 sedaj pa me zanima, kako bi dala da za graf upošteva data1 ali data2 glede na to ali izberemo gostje ali zaposleni?

Ko pa sedaj poženem mi napiše, da 

ERROR:could not find function "%>%"

kljub temu, da imam vse uvožene knjižnice.

**Comment by jaanos** [comment]
Kako pa poganjaš aplikacijo? Meni deluje, če pred tem poženem `libraries.r`, `uvoz1.R` in `vizualizacija.r` (najlažje je, če poženeš kar ukaze `source` v poročilu). Sicer pa aplikacijo vključi v poročilo, tako da na želeno mesto dodaš npr.
```R
    ```{r shiny, echo=FALSE}
    shinyAppDir("shiny", options = list(width = "100%", height = 500))
    ```
```
(brez zamika na začetku vrstic).

Želene podatke lahko izbereš s stavkom `if`, npr.
```R
  output$graf <- renderPlot({
    if (input$osebe == "Gosti") {
      data <- (tabela2 %>% filter(drzava == input$drzava) %>% group_by(leto) %>%
                 summarise(stevilo = sum(stevilo_gostov, na.rm = TRUE)))
    } else {   
      data <- (tabela3 %>% filter(drzava == input$drzava) %>% group_by(leto) %>%
                 summarise(stevilo = sum(stevilo_zaposlenih, na.rm = TRUE)))
    }
    ggplot(data, aes(x = factor(leto), y = stevilo)) + geom_col() +
      xlab("Leto") + ylab("Število oseb")
  })
```
Pri obeh primerih je bilo potrebno dodati še `group_by`, da ti loči podatke po letih. Podatki za os `x` so spremenjeni v faktor, da ti letnic ne izpiše kot decimalke. Pazi še na to, da imaš za Nemčijo različna imena v obeh razpredelnicah, zato ti enih ne prikaže - najlažje bo, če v eni razpredelnici spremeniš ime, tako da bo v obeh isto.
